{
 "title": "Pizza dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "logs(correct)",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"jwt-pizza-service-dev\"} |= `` | json"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(http_requests_avg_latency_ms_milliseconds)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(purchases_avg_latency_ms_milliseconds)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizzas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "rate(purchases_total[1m]) * 60", "legendFormat": "__auto" },
    {
     "expr": "rate(purchases_failure[1m]) * 60",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(purchases_total_cost[1m]) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU and memory usage percentage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "system_cpu_usage_percent", "legendFormat": "__auto" },
    { "expr": "system_memory_usage_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Authentication attempts/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    { "expr": "rate(auth_success_total[1m])", "legendFormat": "__auto" },
    { "expr": "rate(auth_failure_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    { "expr": "active_users_ratio", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "HTTP requests/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    { "expr": "sum(http_requests_total)", "legendFormat": "__auto" },
    { "expr": "sum(http_requests_get_total)", "legendFormat": "__auto" },
    { "expr": "sum(http_requests_post_total)", "legendFormat": "__auto" },
    { "expr": "sum(http_requests_put_total)", "legendFormat": "__auto" },
    {
     "expr": "sum(http_requests_delete_total)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}